# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v1
      with:
        python-version: '3.9.16'

    #install dependencies
    - name: Install Dependencies
      run: pip install -r requirements.txt


    - name: Copy Python file to EC2 via SSH Key
      uses: appleboy/scp-action@master
      with:
        host: ec2-3-128-204-114.us-east-2.compute.amazonaws.com
        username: ec2-user
        port: 8080
        key: ${{ secrets.KEY }}
        source: "src/main/source/main.py"
        target: "~/"
#testtctss
    - name: Run commands to start the Python server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ec2-3-128-204-114.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.KEY }}
        port: 8080
        source: "src/main/source/main.py"
        target: "~/"
        script: |
          killall python
          nohup python main.py > log.txt &
          sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
          sudo iptables -I INPUT -p tcp --dport 8080 -j ACCEPT