# This workflow will set up a Python environment and install any required dependencies to improve the workflow execution time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Due to using Python as the programming language for the project, 
# the set-up below will have some differences with the sample 
# code provided by the professor

name: Python CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #set up Python prgram
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    #install dependencies
    - name: Install Dependencies
      run: pip install -r requirements.txt

    #run the website
    - name: Run commands to start the Python server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ec2-3-128-204-114.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.KEY3 }}
        port: 22
        # As Python does not have a package manager like Maven in Java, we need
        # to copy all necessary files from Github by using git pull
        # (main.py, index.html, index.css, etc)
        script: |
          killall python
          cd VariantFoodScheduler
          # pip install flask-bootstrap
          git stash
          git pop
          git pull
          cd src/main/source
          nohup python main.py > log.txt &
          # As the server using Python Flask waits for user-input (Ctrl - C) to stop running,
          # the build will literally need to wait for a time-out of 10 minutes
          # before the build can complete its workflow and refresh automatically.